#!/bin/bash

# ==============================================================================
# This script is managed by `devws` and sourced by your .bashrc.
# Do not edit this file directly, as it may be overwritten by `devws setup`.
# ==============================================================================

# --- Add ~/.local/bin to PATH ---
# Ensures user-installed binaries are found.
# Idempotent check: only adds the path if it's not already present.
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

# --- NVM (Node Version Manager) Setup ---
# Checks for NVM installation and sources it if found.
export NVM_DIR="$HOME/.config/nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  # Sourcing nvm.sh defines the 'nvm' function. We check if it's already a function.
  if ! type "nvm" > /dev/null 2>&1; then
    \. "$NVM_DIR/nvm.sh"  # This loads nvm
    if [ -s "$NVM_DIR/bash_completion" ]; then
      \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    fi
  fi
fi

# --- SSH-agent Setup for GitHub Access ---
# Starts ssh-agent if a key exists and no agent is already running for the user.
if [ -f "$HOME/.ssh/id_ed25519" ] && ! pgrep -u "$USER" ssh-agent > /dev/null; then
    eval "$(ssh-agent -s)" > /dev/null
    ssh-add "$HOME/.ssh/id_ed25519" > /dev/null 2>&1
fi

# --- Load ~/.env File ---
# Sources a .env file in the home directory if it exists.
# This check prevents it from being sourced multiple times if .bashrc is reloaded.
if [ -f "$HOME/.env" ] && [ -z "$DEVWS_ENV_LOADED" ]; then
    # echo "Loading environment from $HOME/.env" # Optional: uncomment for verbose loading
    source "$HOME/.env"
    export DEVWS_ENV_LOADED=true # Set a flag to prevent re-sourcing
fi
